### ISSUE TITLE
gen-graph command needs to detect non-gzipped data

### ISSUE THREAD

**Issue by kellrott** [bmeg/jsonschemagraph#6]
Example command:
```
(base) $ ./jsonschemagraph/jsonschemagraph gen-graph iceberg/schemas/graph/Patient.yaml TCGA-ESCA/META/Patient.ndjson 
graph Patient
Loaded  [Patient]
Writing:  graph/Patient
ERROR:  gzip: invalid header
```

The input file is not a gzipped file, so they program files.

Maybe detect the `.gz` suffix on the input path and only attempt to decompress if it is there. Or maybe provide a command line flag.

**Comment by matthewpeterkort** [comment]
fixed in: https://github.com/bmeg/jsonschemagraph/blob/fix/duplicate-edges/cmd/gen_graph/main.go#L38-L46
