### ISSUE TITLE
gen-graph outfile name grip compatibility

### ISSUE THREAD

**Issue by kellrott** [bmeg/jsonschemagraph#7]
The `grip load` command looks for a directory using:
 - `edge.json.gz` to find edge files
 - `*.vertex.json.gz` to fine vertex files. 

Currently gen-graph creates `*.Vertex.json`, `OutEdge.json`, `InEdge.json`. If there were changed to `*.vertex.json.gz`, `out.edge.json.gz` and `in.edge.json.gz`, the output files would be able to be loaded into grip directly.

**Comment by matthewpeterkort** [comment]
fixed in https://github.com/bmeg/jsonschemagraph/commit/f09fecb5ba043dabe03bf8b263bfb1ac3df97c67
